import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
 {/* this layout page is rander this hey there at each page this is top of all pages and then after hi there it render childs */}
        <div className="flex items-center justify-between " >
        <div className="w-screen border-b-4 border-indigo-500 h-20">
  <div className="text-3xl py-5 font-bold pl-1">
    medium
  </div>
         </div>
        </div>
        {/* this appbar show at every page */}
        {children}
      </body>
    </html>
  );
}
